// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

type BookIDRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookIDRequest) Reset()         { *m = BookIDRequest{} }
func (m *BookIDRequest) String() string { return proto.CompactTextString(m) }
func (*BookIDRequest) ProtoMessage()    {}
func (*BookIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{1}
}

func (m *BookIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookIDRequest.Unmarshal(m, b)
}
func (m *BookIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookIDRequest.Marshal(b, m, deterministic)
}
func (m *BookIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookIDRequest.Merge(m, src)
}
func (m *BookIDRequest) XXX_Size() int {
	return xxx_messageInfo_BookIDRequest.Size(m)
}
func (m *BookIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookIDRequest proto.InternalMessageInfo

type BookSlugRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookSlugRequest) Reset()         { *m = BookSlugRequest{} }
func (m *BookSlugRequest) String() string { return proto.CompactTextString(m) }
func (*BookSlugRequest) ProtoMessage()    {}
func (*BookSlugRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{2}
}

func (m *BookSlugRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookSlugRequest.Unmarshal(m, b)
}
func (m *BookSlugRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookSlugRequest.Marshal(b, m, deterministic)
}
func (m *BookSlugRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookSlugRequest.Merge(m, src)
}
func (m *BookSlugRequest) XXX_Size() int {
	return xxx_messageInfo_BookSlugRequest.Size(m)
}
func (m *BookSlugRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookSlugRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookSlugRequest proto.InternalMessageInfo

type BookRateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookRateRequest) Reset()         { *m = BookRateRequest{} }
func (m *BookRateRequest) String() string { return proto.CompactTextString(m) }
func (*BookRateRequest) ProtoMessage()    {}
func (*BookRateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{3}
}

func (m *BookRateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookRateRequest.Unmarshal(m, b)
}
func (m *BookRateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookRateRequest.Marshal(b, m, deterministic)
}
func (m *BookRateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookRateRequest.Merge(m, src)
}
func (m *BookRateRequest) XXX_Size() int {
	return xxx_messageInfo_BookRateRequest.Size(m)
}
func (m *BookRateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookRateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookRateRequest proto.InternalMessageInfo

type BoolResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolResponse) Reset()         { *m = BoolResponse{} }
func (m *BoolResponse) String() string { return proto.CompactTextString(m) }
func (*BoolResponse) ProtoMessage()    {}
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{4}
}

func (m *BoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolResponse.Unmarshal(m, b)
}
func (m *BoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolResponse.Marshal(b, m, deterministic)
}
func (m *BoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolResponse.Merge(m, src)
}
func (m *BoolResponse) XXX_Size() int {
	return xxx_messageInfo_BoolResponse.Size(m)
}
func (m *BoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BoolResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Book)(nil), "protos.Book")
	proto.RegisterType((*BookIDRequest)(nil), "protos.BookIDRequest")
	proto.RegisterType((*BookSlugRequest)(nil), "protos.BookSlugRequest")
	proto.RegisterType((*BookRateRequest)(nil), "protos.BookRateRequest")
	proto.RegisterType((*BoolResponse)(nil), "protos.BoolResponse")
}

func init() { proto.RegisterFile("book.proto", fileDescriptor_1e89d0eaa98dc5d8) }

var fileDescriptor_1e89d0eaa98dc5d8 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xca, 0xcf, 0xcf,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0x6c, 0x5c, 0x2c, 0x4e,
	0xf9, 0xf9, 0xd9, 0x4a, 0xfc, 0x5c, 0xbc, 0x20, 0xda, 0xd3, 0x25, 0x28, 0xb5, 0xb0, 0x34, 0xb5,
	0xb8, 0x44, 0x49, 0x90, 0x8b, 0x1f, 0x24, 0x10, 0x9c, 0x53, 0x9a, 0x8e, 0x26, 0x14, 0x94, 0x58,
	0x92, 0x0a, 0x13, 0xe2, 0xe3, 0xe2, 0x71, 0xca, 0xcf, 0xcf, 0x09, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf,
	0x2b, 0x4e, 0x35, 0xda, 0xcb, 0xc4, 0xc5, 0x0d, 0xd6, 0x96, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a,
	0x64, 0xc2, 0xc5, 0xed, 0x9e, 0x5a, 0x02, 0x12, 0x71, 0xaa, 0xf4, 0x74, 0x11, 0x12, 0x85, 0xd8,
	0x5e, 0xac, 0x87, 0x62, 0x97, 0x14, 0x0f, 0xb2, 0xb0, 0x12, 0x83, 0x90, 0x29, 0x17, 0xaf, 0x67,
	0x5e, 0x71, 0x6a, 0x51, 0x89, 0x5f, 0x6a, 0x39, 0x48, 0x48, 0x08, 0x45, 0x81, 0x94, 0x08, 0x12,
	0x0f, 0x6e, 0xb5, 0x12, 0x83, 0x90, 0x33, 0x97, 0x40, 0x68, 0x41, 0x4a, 0x62, 0x49, 0x2a, 0xd4,
	0x95, 0x99, 0x79, 0xe9, 0x42, 0xe2, 0xc8, 0x3a, 0x91, 0x5c, 0x8e, 0xd3, 0x10, 0x7b, 0x2e, 0x3e,
	0x97, 0xd4, 0x9c, 0x54, 0x88, 0x21, 0xf8, 0x1c, 0x8d, 0xcb, 0x00, 0x6b, 0x2e, 0x81, 0xe0, 0xd4,
	0xc4, 0xa2, 0xe4, 0x0c, 0x88, 0x01, 0x7e, 0x89, 0xb9, 0xa9, 0xa8, 0xae, 0x40, 0x0a, 0x52, 0x74,
	0x9f, 0x27, 0x41, 0xa2, 0xc5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xee, 0x2d, 0xc7, 0x75, 0xab,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookServiceClient interface {
	GetBookByID(ctx context.Context, in *BookIDRequest, opts ...grpc.CallOption) (*Book, error)
	InsertNewBook(ctx context.Context, in *Book, opts ...grpc.CallOption) (*BoolResponse, error)
	UpdateBookRating(ctx context.Context, in *BookRateRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	DeleteBookByID(ctx context.Context, in *BookIDRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	SearchBookByName(ctx context.Context, in *BookSlugRequest, opts ...grpc.CallOption) (*Book, error)
}

type bookServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookServiceClient(cc *grpc.ClientConn) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) GetBookByID(ctx context.Context, in *BookIDRequest, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/protos.BookService/GetBookByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) InsertNewBook(ctx context.Context, in *Book, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/protos.BookService/InsertNewBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) UpdateBookRating(ctx context.Context, in *BookRateRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/protos.BookService/UpdateBookRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) DeleteBookByID(ctx context.Context, in *BookIDRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/protos.BookService/DeleteBookByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) SearchBookByName(ctx context.Context, in *BookSlugRequest, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/protos.BookService/SearchBookByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
type BookServiceServer interface {
	GetBookByID(context.Context, *BookIDRequest) (*Book, error)
	InsertNewBook(context.Context, *Book) (*BoolResponse, error)
	UpdateBookRating(context.Context, *BookRateRequest) (*BoolResponse, error)
	DeleteBookByID(context.Context, *BookIDRequest) (*BoolResponse, error)
	SearchBookByName(context.Context, *BookSlugRequest) (*Book, error)
}

// UnimplementedBookServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (*UnimplementedBookServiceServer) GetBookByID(ctx context.Context, req *BookIDRequest) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookByID not implemented")
}
func (*UnimplementedBookServiceServer) InsertNewBook(ctx context.Context, req *Book) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertNewBook not implemented")
}
func (*UnimplementedBookServiceServer) UpdateBookRating(ctx context.Context, req *BookRateRequest) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBookRating not implemented")
}
func (*UnimplementedBookServiceServer) DeleteBookByID(ctx context.Context, req *BookIDRequest) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBookByID not implemented")
}
func (*UnimplementedBookServiceServer) SearchBookByName(ctx context.Context, req *BookSlugRequest) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchBookByName not implemented")
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_GetBookByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetBookByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.BookService/GetBookByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetBookByID(ctx, req.(*BookIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_InsertNewBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Book)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).InsertNewBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.BookService/InsertNewBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).InsertNewBook(ctx, req.(*Book))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_UpdateBookRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).UpdateBookRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.BookService/UpdateBookRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).UpdateBookRating(ctx, req.(*BookRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_DeleteBookByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).DeleteBookByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.BookService/DeleteBookByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).DeleteBookByID(ctx, req.(*BookIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_SearchBookByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookSlugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).SearchBookByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.BookService/SearchBookByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).SearchBookByName(ctx, req.(*BookSlugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBookByID",
			Handler:    _BookService_GetBookByID_Handler,
		},
		{
			MethodName: "InsertNewBook",
			Handler:    _BookService_InsertNewBook_Handler,
		},
		{
			MethodName: "UpdateBookRating",
			Handler:    _BookService_UpdateBookRating_Handler,
		},
		{
			MethodName: "DeleteBookByID",
			Handler:    _BookService_DeleteBookByID_Handler,
		},
		{
			MethodName: "SearchBookByName",
			Handler:    _BookService_SearchBookByName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book.proto",
}
